### ISSUE TITLE
Have stripe send a receipt when credit card payment is successful

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#103]
See docs: https://docs.stripe.com/receipts?payment-ui=direct-api

**Comment by lilliputten** [comment]
@cmutel I'm currently implementing just sending of a message with attached pdf. Is that ok?

**Comment by cmutel** [comment]
The receipt should come from Stripe (see the docs I linked)

**Comment by lilliputten** [comment]
I see that it's impossible to check this thing in the test mode, according to [docs](https://docs.stripe.com/api/payment_intents/confirm#confirm_payment_intent-receipt_email) ("...for a payment in live mode...").

So, I'm just finishing it and pushing for a testing.

Should I remove the sending of emails with invoices after successful payments?
