### ISSUE TITLE
Update invoice creation for different cases

### ISSUE THREAD

**Issue by lilliputten** [sentier-dev/dds_registration#104]
It looks a bit wrong ("Event") for membership:

![2024-04-04-19-26-31](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/e8f5750f-d8af-4ea4-b521-0bba5e2a9d9b)

@cmutel, pls, confirm the need for these corrections and provide the correct texts?

**Comment by cmutel** [comment]
@lilliputten Yeah, this is wrong on many levels. We need another refactoring.
