### ISSUE TITLE
Layout: `/membership/apply` improvements

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#113]
<img width="1389" alt="Screenshot 2024-04-05 at 21 27 08" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/6c962d56-6d53-400b-8d5d-43bfbf3d9b8c">

I would prefer to not have to manually lay out the form, but do this via CSS (and then collapse to one column on smaller screens). See https://docs.djangoproject.com/en/5.0/ref/forms/widgets/#styling-widget-instances.

Instead of:

```
A
B
```

It would be nicer to have 
```
A    B
````

for the two choices given.

Also, the text "Business membership is not yet available, sorry." should be below the membership type choice.

**Comment by cmutel** [comment]
See also https://github.com/Depart-de-Sentier/dds_registration/issues/114

**Comment by lilliputten** [comment]
Is this task about the horizontal layout for the payment method radio group? (I can't see the target of the task in its description.) 

Or is this thing only a part of the task?

About styling of the radio groups: I couldn't find a way to pass the class name to the widget (it didn't work here in the traditional way). Probably, the next option is to define our widget class (based on `RadioSelect`).

**Comment by cmutel** [comment]
> Is this task about the horizontal layout for the payment method radio group? (I can't see the target of the task in its description.)

Yes, exactly.

> About styling of the radio groups: I couldn't find a way to pass the class name to the widget (it didn't work here in the traditional way). Probably, the next option is to define our widget class (based on RadioSelect).

Sorry man, but I posted a link to the documentation on exactly how to do this!? E.g. adding:

`membership_type.widget.attrs.update({"class": "special-label"})` to the form gives:

<img width="554" alt="Screenshot 2024-04-06 at 15 47 48" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/728230a0-f8f7-403e-b59e-ab881c27445f">

Do you mean that you want the attach the class to a higher level tag? In that case I think we need to write the form out manually.

**Comment by lilliputten** [comment]
As I remember from my experiments, this approach didn't have any effect for radios. (Mb, I lost smth, it'd be good to re-check it first.)

**Comment by lilliputten** [comment]
I just saw this: "Also, the text "Business membership is not yet available, sorry." should be below the membership type choice."

It was removed in the PR as an unused block.

Should it be reverted?
