### ISSUE TITLE
Bug: Profile page doesn't show payment method correctly

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#129]
<img width="1335" alt="Screenshot 2024-04-06 at 08 44 37" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/a5fc30f6-7e1f-470f-ba6b-4bc2df80db42">

**Comment by lilliputten** [comment]
It also seems there that table styles are broken now too. Going to fix it later. See issue #132.
