### ISSUE TITLE
In the event admin panel there should be a link to the event in the main site

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#22]
This would help development and for people entering new events.

**Comment by lilliputten** [comment]
@cmutel

Which kind of link do you mean?

A link to create a new registration for the user? (This options seems to be more likely. I'm going to start this one if I don't receive a response soon.)

Or we should have a public (?) list of events and pages containing data for each event?

**Comment by cmutel** [comment]
Fixed in #26
