### ISSUE TITLE
User profile page: Provide link to invoice 

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#36]
People lose emails. We can store the PDF and provide it or generate it dynamically.

@lilliputten Please provide a concept for this issue before starting the coding. Thanks!

**Comment by lilliputten** [comment]
> People lose emails. We can store the PDF and provide it or generate it dynamically.
> 
> @lilliputten Please provide a concept for this issue before starting the coding. Thanks!

I've already added these links (to payment info, which is just a template now) and to invoice download in the 'event registration successfully created' page. (But this page is temporary too.)

I can add it to the registration entry on the profile page.

Alternatively, we can create a dedicated 'view registration' page (if we going to have more data for registrations) and place these links there.

I meant this table:

![2024-03-18-01-05](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/e83e9094-bb7e-4d8c-b058-8fa6cfa82d0f)

It's possible to add an extra button with a pdf icon to download an invoice there.

**Comment by cmutel** [comment]
> It's possible to add an extra button with a pdf icon to download an invoice there.

This is already good enough.

**Comment by lilliputten** [comment]
Added a link for invoice download to the registrations list on the profile page. PR #52

Are we sure that a dedicated page with a registration information isn't necessary?

**Comment by cmutel** [comment]
> Are we sure that a dedicated page with a registration information isn't necessary?

No, this is also needed, but less important than other things for now.
