### ISSUE TITLE
Provide link to admin in the standard header

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#37]

**Comment by lilliputten** [comment]
I don't completely understand it: do you offer to show the admin link for all the users? (Is that safe?)

Or, mb, it should be shown only for specific users (for `admin`, eg)?

**Comment by cmutel** [comment]
> I don't completely understand it: do you offer to show the admin link for all the users? (Is that safe?)

Yes, the link is for everyone - just because the link is there doesn't mean that they can log into the admin site :)

**Comment by lilliputten** [comment]
Added in PR #55.
