### ISSUE TITLE
Create a landing content for the main page

### ISSUE THREAD

**Issue by lilliputten** [sentier-dev/dds_registration#39]
To check: do we need a redirect from main page to user's profile if the user is already logged in? Or it could be useful for users to get to that main page sometimes (for some reason)?

**Comment by cmutel** [comment]
If the user isn't logged in, then something like:

<img width="472" alt="Screenshot 2024-03-21 at 13 02 49" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/3dec6e45-ac5a-4fad-b6fb-86410b5f231f">

Where:
- **A** is the header
- **B** is text on membership, with a button to `/membership`
- **C** is the image here: https://github.com/Depart-de-Sentier/Depart-de-Sentier.github.io/blob/main/images/dds-painting.png (Should disappear on smaller screens)
- **D** is the table of open events

If the user is logged in, then something like:

<img width="465" alt="Screenshot 2024-03-21 at 13 05 58" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/5661a28e-8498-4261-a2a2-ec83647d61fe">

Where:
- **A** is the header
- **B** is a reminder for users who aren't members that they can join DdS (with a button to `/membership`)
- **C** is a table of the events that user is registered for
- **D** is a table of other public events

**Comment by cmutel** [comment]
You can play with the layout, I am not a designer!

**Comment by lilliputten** [comment]
What's this: '_B is a reminder for users who aren't members that they can join DdS (with a button to /membership)_'? Do we need to add another column like `is_member`? Or it's about the membership on a different site? Shouldn't it be data-driven (we just show this block, not trying to determine if the current user is a member or not; just like a simple advertisement)?

UP: I see #50 (Feature: DdS membership) -- probably, there is enough information on it?

**Comment by cmutel** [comment]
> UP: I see https://github.com/Depart-de-Sentier/dds_registration/issues/50 (Feature: DdS membership) -- probably, there is enough information on it?

Yes, I need to close this issue first. For now it can be a link to example.com.

**Comment by lilliputten** [comment]
Do we have to use an `active` property for events, to show if an event is available for registration and/or to be listed on site?

Mb, one more property: `closed` to show that registrations are finished?

**Comment by cmutel** [comment]
Better to just use `can_register` from https://github.com/Depart-de-Sentier/dds_registration/commit/b983e89bef553bc5b775f70571ff6a5d2931575e

**Comment by cmutel** [comment]
We already have `public` - this is also needed to be listed on the homepage.

**Comment by lilliputten** [comment]
Are these texts for the part 'B' (membership texts for anonymous and logged users) already ready? M.b, I can use some drafts?

**Comment by cmutel** [comment]
Part B text:

Become a member! Membership is for one calendar year, and costs €25 for academics and €50 for everyone else. Members get a newsletter, a vote at the General Assembly, and discounts on selected DdS events.

**Comment by lilliputten** [comment]
Is it for non-logged users? Or for logged ones too?

No links/buttons there?

**Comment by cmutel** [comment]
It is for everyone who isn't a member (see https://github.com/Depart-de-Sentier/dds_registration/pull/57/files#diff-ba495e5b9a7a2a85ab521cb77e5cfc5da5e8e53c92657ad40a5e83a9919546c3R113).

"Become a member" links to the `membership` view (you need to write this).

**Comment by lilliputten** [comment]
I'm going to use the same text for logged users too. It's possible to change it later.

**Comment by lilliputten** [comment]
Probably, to use a button for 'Become...' is more 'clickable' option?

Here are some probes (ca lickable title and a button):

![2024-03-25-17-56-48](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/9986b67b-daa5-434d-8b12-edc9945e6bfc)

**Comment by cmutel** [comment]
Yes to the button.
We only need the button then, not the link as well.
I think with the picture the way it is this needs to be on a white or off-white background.
Same text for anyone who isn't a member, regardless of whether they are logged in or not.
