### ISSUE TITLE
User `email` should be unique

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#44]
Probably best to do this directly in the database:

From [SO](https://stackoverflow.com/questions/66737754/django-3-setting-user-email-to-be-unique-minimal-viable-solution) (code in `models.py`):

```python
from django.contrib.auth.models import User
User._meta.get_field('email')._unique = True
```

We can also modify the sign up and other forms to [do this check and provide better feedback](https://stackoverflow.com/questions/33306409/django-best-way-to-have-unique-email-in-user-model).

**Comment by lilliputten** [comment]
Already implemented in issue #38.
