### ISSUE TITLE
Non add-on `RegistrationOption`: Only one option should be selectable in the form

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#45]
These choices are exclusive. Also, we need to check in the backend as well as people can be tricky.

**Comment by lilliputten** [comment]
See PR #48.

![2024-03-21-01-09-47](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/7a422bd3-a6e4-42dc-8bad-450016bdb2c4)
