### ISSUE TITLE
Feature: Unified billing

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#65]
Part of #63.

We have a single page which handles billing. It can be reached by various entry points, but the underlying logic and display should be the same, or at least similar.

## Events

Entry URL should be something like `/billing/<event id>`. 

Users must be logged in, and registered for the event - otherwise they get redirected to the homepage. If they are registered, then they have chosen a `RegistrationOption`, so we can use that to look up the price and currency.

## Membership

Entry URL should be something like `/billing/membership`. 

The first thing users need to do is select if this is an academic, business, or normal membership.

## Creating the bills

From either path, the user then needs to choose how they want to pay - either Credit Card or Invoice. You get to choose what that UI looks like. 

We should also display the name and address that we have for that user account. Users can make changes *for this specific invoice or bill* if needed. There is also a question for any extra information they might want to add to the Invoice (help text is "Any additional text for the invoice, such as a reference or purchase order number"). 

If they choose the Invoice option, then we tell them that we have emailed the invoice (and we do that), and display a button for them to download that invoice (if they prefer that). We need to use and also save the extra information provided by the user in the `data` field.

If they chose the Credit Card approach, then we create the bill using the Stripe API, and if there is a successful callback/webhook, we change the registration status.

**Comment by lilliputten** [comment]
That note about 'Users can make changes for this specific invoice or bill if needed' right after the requirement to show the name and address -- what is it about?

Did you mean that the user can change name and address (for the invoice/payment? not for the account?)?

**Comment by lilliputten** [comment]
> We need to use and also save the extra information provided by the user in the data field.

In the model, the `data` field has a 'JSON' type. Should we ask the user to enter the JSON code?

Or we should pack some (which?) extra data into JSON and save it there? It does not make sense (for me): it seems that it's easier to have a dedicated field for `payment_method` and `extra_invoice_text`.

Or did you mean other data?

UP: See that brief explanation in the field comment: 'Includes the various item descriptions, prices, and currencies and any other necessary info'. But still don't understand the usage.

**Comment by lilliputten** [comment]
>  If they are registered, then they have chosen a RegistrationOption

We have `RegistrationOption` as a property of `Registration` model.

Should we take it from registration object (and allow selecting during registration creation)? (At the moment it's the only option in a 'create a registration' form.)

Or to select here (in the billing form)? And store back to the related registration object? Or just use and forget (mb, store to the `data` object)?

**Comment by cmutel** [comment]
> That note about 'Users can make changes for this specific invoice or bill if needed' right after the requirement to show the name and address -- what is it about?
> 
> 
> 
> Did you mean that the user can change name and address (for the invoice/payment? not for the account?)?

Yes, exactly. The invoice address can be different than the users address

**Comment by cmutel** [comment]
> > ...JSON
> There will be different fields according to the template. I can explain more when at home in front of computer.

I don't use the `data` field now, treating it as 'reserved'.

**Comment by lilliputten** [comment]
> > That note about 'Users can make changes for this specific invoice or bill if needed' right after the requirement to show the name and address -- what is it about?
> > Did you mean that the user can change name and address (for the invoice/payment? not for the account?)?
> 
> Yes, exactly. The invoice address can be different than the users address

So, do I need to add columns `name` and `address` to the Invoice model and initialize them with the user's values?

**Comment by cmutel** [comment]
> >  If they are registered, then they have chosen a RegistrationOption
> 
> 
> 
> We have `RegistrationOption` as a property of `Registration` model.
> 
> 
> 
> Should we take it from registration object (and allow selecting during registration creation)? (At the moment it's the only option in a 'create a registration' form.)
> 
> 
> 
> Or to select here (in the billing form)? And store back to the related registration object? Or just use and forget (mb, store to the `data` object)?

You have to choose one registration option as part of the registration process

**Comment by lilliputten** [comment]
Added billing form for event registration:

![2024-03-28-21-31-56](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/7037bb68-0014-4c37-99c0-00fbbb5ed5d8)

**Comment by lilliputten** [comment]
Added intermediate page ('The invoice has been successfully created'):

![2024-03-29-01-07-24](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/838a1295-a304-4a49-bbf9-d3886a80c97a)

Probably, we should change texts and add some stylizations.

**Comment by lilliputten** [comment]
Updated generation of the pdf invoice:

![2024-03-29-01-12-58](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/863dd413-9027-4bf0-a767-42e6e7de5ad7)

Currency is taken from the option data.

**Comment by lilliputten** [comment]
At the moment, `INVOICE_TEMPLATES` property doesn't affect the invoice PDF. Should I change smth there according to this data?

**Comment by cmutel** [comment]
> At the moment, INVOICE_TEMPLATES property doesn't affect the invoice PDF. Should I change smth there according to this data?

I need to give you some guidance on this, so let's stick with what we have for now. Thanks.

**Comment by lilliputten** [comment]
Stripe payment system is finished in general in [#2875299](https://github.com/Depart-de-Sentier/dds_registration/commit/2875299).

There should be done some minor tasks:

- Add membership options to determine the cost.
- Remove stripe proceed page own buttons.
- Restructure billing code (divide by event/membership; m.b., by invoice/stripe).
- Send emails for membership succeed pages (`send_membership_membership_success_message`?).
- Reorganize urls (using submodules/subpaterns).
