### ISSUE TITLE
Membership start page: Some fixes

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#68]
<img width="901" alt="Screenshot 2024-03-29 at 07 31 22" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/1efbeb7e-d572-45f7-ab88-56dc03df37a8">

Instead of radio buttons here, please make a big (virtual) button where we can add an icon and some text. We need to explain what these are. For now please use dummy text and icon.

Clicking any of these buttons should lead on to the payment page directly - there doesn't need to be a separate "proceed" button.

**Comment by cmutel** [comment]
Users who aren't logged in shouldn't see the form at all - they should be redirected to account login or creation with the flash message "You have to have an account before you can register for membership". We could also embed the signup form on the membership page if that is a better user experience.

**Comment by lilliputten** [comment]
Implemented as part of the issue #65, commit [#7ceb816](https://github.com/Depart-de-Sentier/dds_registration/commit/7ceb8168e79522ef251355bb27869a3147a9f58f).

![2024-03-30-18-11-43](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/b5b0c331-55f4-4243-ae2e-7c7dfcdfb6c7)

![2024-03-30-18-38-20](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/7ae4a3a5-1373-40fb-a325-9ca67ee83e61)
