### ISSUE TITLE
New registration form: fixes

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#70]
<img width="786" alt="Screenshot 2024-03-29 at 07 49 24" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/22989727-a13a-464f-a7fa-07535b4cafab">

No need for the labels, just show name, description, and then show "Registration open from {date} to {date} (inclusive)."

**Comment by lilliputten** [comment]
Implemented as part of #93, commit [#4209374](https://github.com/Depart-de-Sentier/dds_registration/commit/4209374).

![2024-04-03-23-55-34](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/7626d92b-8055-4606-9a22-50342c348a4d)
