### ISSUE TITLE
Payment page: Fixes

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#71]
<img width="1020" alt="Screenshot 2024-03-29 at 08 02 26" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/0cc90ee7-ed40-4424-9a20-10dc0a8b02fa">

- [x] We don't need to tell the user their own email, and this is in any case in the header.
- [x] Instead of `Event: Foo`, change form legend to "Payment for {even title}"
- [x] Don't show "Registration: cmutel@gmail.com, Application submitted, March #d, 2024" at all
- [ ] Instead of a drop down for payment, this should be a radio box with horizontal buttons, a graphical indication of what is chosen (clicking on one should "inset" or highlight it), and the labels should be "Credit Card" or "Invoice". They should also have icons.
- [x] Don't show the template, this is an internal implementation detail.
- [x] Change "Extra invoice text" to "Extra information on the invoice, such as reference or purchase order number"
- [ ] Change "Save" button label to "Pay now" (if credit card) or "Email me invoice" (if invoice)

**Comment by lilliputten** [comment]
> Change "Save" button label to "Pay now" (if credit card) or "Email me invoice" (if invoice)

Do you want to change the button text dynamically, depending on the chosen payment option? (Just clarifying, in order to avoid misunderstandings.)

**Comment by cmutel** [comment]
> Do you want to change the button text dynamically

Yes please.

**Comment by lilliputten** [comment]
Partially implemented as part of #93, commit [#4209374](https://github.com/Depart-de-Sentier/dds_registration/commit/4209374).

TODO:

- Change the submit button text dynamically depending on the payment method control state: 'Save' for 'INVOICE' and 'Pay now' for 'STRIPE'
- Make payment method control inline, add option icons. To clarify: Add 'highlighting'? Change names to 'Credit Card' or 'Invoice'? Probably it'll be necessary to redefine widget class.

![2024-04-03-23-47-57](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/025d0b8d-968e-4fea-91af-5c3b6dc9c919)

**Comment by lilliputten** [comment]
This task hasn't been finished yet: there are still 2 todo's:

- Change the submit button text dynamically depending on the payment method control state: 'Save' for 'INVOICE' and 'Pay now' for 'STRIPE'.
- Make payment method control inline, add option icons. To clarify: Add 'highlighting'? Change names to 'Credit Card' or 'Invoice'? Probably it'll be necessary to redefine widget class.

**Comment by cmutel** [comment]
> Change the submit button text dynamically depending on the payment method control state: 'Save' for 'INVOICE' and 'Pay now' for 'STRIPE'.

It can just read "Pay now"

> Make payment method control inline, add option icons. To clarify: Add 'highlighting'? Change names to 'Credit Card' or 'Invoice'? Probably it'll be necessary to redefine widget class.

This is OK for now. We can change in future but we can release with what we have.
