### ISSUE TITLE
Billing success page: fixes

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#72]
I think the same template is used if Stripe went through, or if an invoice was generated. But this needs changes - the language should be different.

<img width="816" alt="Screenshot 2024-03-29 at 08 17 15" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/48306b45-b462-4050-88bd-4ce8e77b0604">

If the user paid by credit card, then redirect to their user account page with a flash message "Registration is complete".

If they chose the invoice, then display the following:

Header: Registration complete pending payment

Text: The invoice for {event title} has been mailed to your user account email address. You can also download it directly:

Buttons: [Download invoice] [My account] [Homepage]

**Comment by lilliputten** [comment]
Implemented as part of #65 in commit [ed9e9b4](https://github.com/Depart-de-Sentier/dds_registration/commit/ed9e9b4):

Updated success page for event registration, updated success email message for event registration creation (it's sent after invoice creation now, and contains different texts for invoice and stripe payment methods).

![2024-04-01-14-44-36](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/1af3a460-7920-45a9-ad6e-46cda1ad979c)
