### ISSUE TITLE
Bug: Invoice dates

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#73]
Invoice date string interpolation is broken: `Invoice date: March #d, 2024`

**Comment by lilliputten** [comment]
I see my comment (in `dds_registration/core/constants/date_time_formats.py`) for this issue (wasn't sure that it's a real bug at that time):

> dateFormat = "%B %#d, %Y"  # TODO: A day without zero? NOTE: It seems to be non-cross-platform: '%#d' is for windows and '%-d' -- for unix
