### ISSUE TITLE
Invoice email: fixes

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#74]
- [x] Include the invoice as an attachment
- [x] Change title from "Already created a registration for the event Foo" to "[DdS]: You have registered for {event title}"
- [x] Text should be changed to:

Hi {name}! Thanks for registering for {event title}. You have chosen to pay by bank transfer. Your invoice is attached, but can also be download anytime at {download link}. If you need to change your payment method (e.g. pay by credit card), you can do that at {payment link}. Please note that payment must be made with {payment days}.

If you have questions or comments, you can reach us at events@d-d-s.ch.

**Comment by lilliputten** [comment]
I'm not sure if it'll be (easily) possible to add an attachment with a stock `user.email_user`. Would it be enough to send a link to download the invoice?

**Comment by cmutel** [comment]
> I'm not sure if it'll be (easily) possible to add an attachment with a stock user.email_user. Would it be enough to send a link to download the invoice?

Please mark the tasks you have done, and then assign the issue to me - I will figure it out.

**Comment by lilliputten** [comment]
> You have chosen to pay by bank transfer

At the moment at this stage, we send this message on an ANY registration creation (before invoice creation). Is that ok to say "about bank transfer" for both stripe and invoice (and potentially) wise methods?

If we try to get the generated invoice, we will get the exception "No invoice found for the event 'The first event' (first)".

**Comment by lilliputten** [comment]
~~Do I need to keep a link to invoice creation page (`billing/event/<str:event_code>`) in the message?~~ (it is already inside the message body. Had fixed it.)

Do I need to keep information about the chosen option?

**Comment by lilliputten** [comment]
Changes in #65 (commit https://github.com/Depart-de-Sentier/dds_registration/commit/5fa2043): Updated an email message subject and body for the registration creation.

Current message view:

![2024-03-30-19-35-56](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/065409e2-1dcd-4a4a-927f-c340c901e50c)

**Comment by lilliputten** [comment]
I get the point: this message should be sent after the invoice creation, but not after the registration has created. I'm going to copy this message for that event, and we have to modify this specific message again then.

**Comment by cmutel** [comment]
> I get the point: this message should be sent after the invoice creation, but not after the registration has created.

Yes, and this issue is just for the email sent when someone pays by invoice. It's a separate process and email for when they pay by card. Can we get a receipt PDF from Stripe automatically? Or will Stripe send this themselves?

**Comment by lilliputten** [comment]
> Can we get a receipt PDF from Stripe automatically? Or will Stripe send this themselves?

I think not, as we deal with Stripe only through API.

We can send it at our own later (for a different event). I'm going to return to this issue later.

**Comment by lilliputten** [comment]
Added updates as part of #65 in commit [ed9e9b4](https://github.com/Depart-de-Sentier/dds_registration/commit/ed9e9b4):

Updated success page for event registration, updated success email message for event registration creation (it's sent after invoice creation now, and contains different texts for invoice and stripe payment methods).

**Comment by lilliputten** [comment]
This task probably could be closed due to #84.

**Comment by cmutel** [comment]
Let's actually implement the attachment first 😛

**Comment by lilliputten** [comment]
> Let's actually implement the attachment first 😛

Yep, you're right. I thought at first that you've already implemented the whole task.

But I can't see the issue for the rest of the task.

**Comment by cmutel** [comment]
I will take it from here, we need to do #94 as well.

**Comment by lilliputten** [comment]
Created this one: #96.

**Comment by lilliputten** [comment]
Is it finished? (In #84?)
