### ISSUE TITLE
Add membership options to determine the cost.

### ISSUE THREAD

**Issue by lilliputten** [sentier-dev/dds_registration#78]

**Comment by lilliputten** [comment]
@cmutel Can you, pls, complete the description of this task? (If there are some things what I shouldn't forget during the implementation?)

**Comment by cmutel** [comment]
You have convinced me that trying to squeeze membership into events doesn't really make sense. So I think for now it is fine to hard-code the amounts (this can only change max once per year as it is governed by the General Assembly).

25 EUR for academic, 50 EUR for normal

**Comment by lilliputten** [comment]
Do you mean that we are not refusing to implement membership options (both with the type of membership and with the currency), but instead will use the currency in euros and provide these two hard-coded options?

(For me those membership options looked quite logical and natural.)

**Comment by cmutel** [comment]
We cold create a corresponding `MembershipOptions` table, but let's push that to v2. For now we have two hard coded choices with fixed prices and a single currency - that should be enough.
