### ISSUE TITLE
Add stripe product names for respective payments

### ISSUE THREAD

**Issue by lilliputten** [sentier-dev/dds_registration#81]
There should be different products for membership and event registration payments.

Now this value comes from a single source: environment variable `STRIPE_PAYMENT_PRODUCT_NAME`, and it's the same for all the payments.

**Comment by lilliputten** [comment]
@cmutel Check this task, pls: do we really need it and in which way?

**Comment by cmutel** [comment]
I think we need to shift to the heavier payments intent API. I will work on it.

**Comment by lilliputten** [comment]
> I think we need to shift to the heavier payments intent API. I will work on it.

It's already being used there. What do you mean by that?

UP: Do you want to use that API differently? In a kinda more sophisticated way?

**Comment by lilliputten** [comment]
Not actual, as we don't use product names anymore in stripe payment intent api.
