### ISSUE TITLE
Send invoices as email message attachments on membership and event success

### ISSUE THREAD

**Issue by lilliputten** [sentier-dev/dds_registration#84]
See #74 (subtask 1).

**Comment by cmutel** [comment]
Being worked on in https://github.com/Depart-de-Sentier/dds_registration/tree/email-attachments

**Comment by lilliputten** [comment]
> Being worked on in https://github.com/Depart-de-Sentier/dds_registration/tree/email-attachments

Thanks, let me know when it's ready: probably, there will be some conflicts. I'll try to merge it asap.

**Comment by lilliputten** [comment]
@cmutel I see that you changed email's content type to html and we have to change email templates too?

UP: I see the point: you used `html_content` instead of `plain_text_content`. I'm going to change it to the plain content (we use only plain text templates now).
