### ISSUE TITLE
Class `btn btn-default` should have outline

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#85]
<img width="622" alt="Screenshot 2024-04-02 at 09 21 54" src="https://github.com/Depart-de-Sentier/dds_registration/assets/645217/5f9964eb-4da5-482f-8038-fad1d3bd151f">

It's easy for users not to understand that there aren't buttons without the outline.

**Comment by lilliputten** [comment]
Those buttons in those groups that are links remain non-outlined but underlined.

![2024-04-02-16-59-12](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/35ce6492-6d69-4aa8-8bd9-993a40b491e9)

**Comment by cmutel** [comment]
Let's put an outline on every button. Isn't this a simple CSS rule?

**Comment by lilliputten** [comment]
Probably, it'd be better to remove underlines from link buttons. (I'm not sure that we have to mark this kind of ui elements. But it looks a bit sloppy.)

![2024-04-02-17-09-06](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/c74eecba-e459-42e9-a8e8-29ba0001c054)

**Comment by cmutel** [comment]
```css
a .btn-link {
  text-decoration: none;
}
```

Quicker to fix than to chat about :)

**Comment by lilliputten** [comment]
No. That's wrong (but close). But I get the idea. And the question wasn't about the exact technical solution. But more about UX (still not sure that this approach is good).
