### ISSUE TITLE
Implement sending receipt as attachment on successful payment

### ISSUE THREAD

**Issue by lilliputten** [sentier-dev/dds_registration#96]
See previous (base) tasks: #74 ("Invoice email: fixes"), #84 ("Send invoices as email message attachments on membership and event success").

See also: #94 ("Refactor invoice PDF creation").

There is required to pass real generated invoice data to updated `email_user` methods.

**Comment by lilliputten** [comment]
@cmutel  What do you mean by 'receipt'? Do we have to send not only an invoice, but smth else alongside with it (or instead)?

**Comment by cmutel** [comment]
An invoice is something you have to pay, a receipt is for when you have already paid.

Can you do #103? I will do the work needed for sending receipts from paid invoices.

**Comment by lilliputten** [comment]
Is that finished now (#84), or we have to complete smth else here?
