### ISSUE TITLE
User profile page should show membership status

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#99]
Either show: "Member since {year}" or show "Not yet a DdS member. Apply for membership here" with a link,

**Comment by lilliputten** [comment]
Implemented as part of #101, commit [#307779b](https://github.com/Depart-de-Sentier/dds_registration/pull/109/commits/307779b).

![2024-04-05-00-46-29](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/6818a749-0eaa-4b46-863d-9ffb8e0921ec) ![2024-04-05-00-46-39](https://github.com/Depart-de-Sentier/dds_registration/assets/6855837/2cb2bc64-b808-4ead-9972-578c3c82fda5)
